
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface RoadmapDownloaderProps {
  skillTitle: string;
  roadmap: Array<{
    phase: string;
    title: string;
    description: string;
    duration: string;
    topics: string[];
  }>;
}

const RoadmapDownloader = ({ skillTitle, roadmap }: RoadmapDownloaderProps) => {
  const downloadRoadmap = () => {
    const roadmapContent = `
${skillTitle} Learning Roadmap
${'-'.repeat(skillTitle.length + 17)}

${roadmap.map((item, index) => `
${index + 1}. ${item.title}
Phase: ${item.phase}
Duration: ${item.duration}
Description: ${item.description}

Topics to Cover:
${item.topics.map(topic => `• ${topic}`).join('\n')}

${'='.repeat(50)}
`).join('')}

Generated by SkillSprout
Visit us at: https://skillsprout.app
    `;

    const blob = new Blob([roadmapContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${skillTitle.replace(/\s+/g, '_')}_roadmap.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button onClick={downloadRoadmap} variant="outline" className="flex items-center gap-2">
      <Download className="w-4 h-4" />
      Download Roadmap
    </Button>
  );
};

export default RoadmapDownloader;
